[env:wt32-eth01]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

upload_port = COM19
upload_speed = 115200
extra_scripts =
    pre:scripts/version_pre.py
    post:scripts/version_post.py
 
build_flags =
    -D ETH_PHY_ADDR=1
    -D ETH_PHY_POWER=16
    -D ETH_PHY_MDC=23
    -D ETH_PHY_MDIO=18
    -D ETH_CLK_MODE=ETH_CLOCK_GPIO0_IN
    -D WIFI_SSID=\"\"
    -D WIFI_PASS=\"\"

lib_deps =
    bblanchon/ArduinoJson@^7
    earlephilhower/ESP8266Audio@^1.9.7
    adafruit/Adafruit GFX Library@^1.11.10
    adafruit/Adafruit SSD1306@^2.5.13
